//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hugo_LAND.Client.HugoLandServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_Land.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class ClassDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClasseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseDexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseVitaliteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomClasse {
            get {
                return this.NomClasseField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClasseField, value) != true)) {
                    this.NomClasseField = value;
                    this.RaisePropertyChanged("NomClasse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseDex {
            get {
                return this.StatBaseDexField;
            }
            set {
                if ((this.StatBaseDexField.Equals(value) != true)) {
                    this.StatBaseDexField = value;
                    this.RaisePropertyChanged("StatBaseDex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseInt {
            get {
                return this.StatBaseIntField;
            }
            set {
                if ((this.StatBaseIntField.Equals(value) != true)) {
                    this.StatBaseIntField = value;
                    this.RaisePropertyChanged("StatBaseInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseStr {
            get {
                return this.StatBaseStrField;
            }
            set {
                if ((this.StatBaseStrField.Equals(value) != true)) {
                    this.StatBaseStrField = value;
                    this.RaisePropertyChanged("StatBaseStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseVitalite {
            get {
                return this.StatBaseVitaliteField;
            }
            set {
                if ((this.StatBaseVitaliteField.Equals(value) != true)) {
                    this.StatBaseVitaliteField = value;
                    this.RaisePropertyChanged("StatBaseVitalite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeroDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_Land.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class HeroDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstConnecteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NiveauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomHeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatDexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatIntField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatVitaliteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstConnecte {
            get {
                return this.EstConnecteField;
            }
            set {
                if ((this.EstConnecteField.Equals(value) != true)) {
                    this.EstConnecteField = value;
                    this.RaisePropertyChanged("EstConnecte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Niveau {
            get {
                return this.NiveauField;
            }
            set {
                if ((this.NiveauField.Equals(value) != true)) {
                    this.NiveauField = value;
                    this.RaisePropertyChanged("Niveau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomHero {
            get {
                return this.NomHeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NomHeroField, value) != true)) {
                    this.NomHeroField = value;
                    this.RaisePropertyChanged("NomHero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatDex {
            get {
                return this.StatDexField;
            }
            set {
                if ((this.StatDexField.Equals(value) != true)) {
                    this.StatDexField = value;
                    this.RaisePropertyChanged("StatDex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatInt {
            get {
                return this.StatIntField;
            }
            set {
                if ((this.StatIntField.Equals(value) != true)) {
                    this.StatIntField = value;
                    this.RaisePropertyChanged("StatInt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatStr {
            get {
                return this.StatStrField;
            }
            set {
                if ((this.StatStrField.Equals(value) != true)) {
                    this.StatStrField = value;
                    this.RaisePropertyChanged("StatStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatVitalite {
            get {
                return this.StatVitaliteField;
            }
            set {
                if ((this.StatVitaliteField.Equals(value) != true)) {
                    this.StatVitaliteField = value;
                    this.RaisePropertyChanged("StatVitalite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Authentification", ReplyAction="http://tempuri.org/IAccountService/AuthentificationResponse")]
        string Authentification(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Authentification", ReplyAction="http://tempuri.org/IAccountService/AuthentificationResponse")]
        System.Threading.Tasks.Task<string> AuthentificationAsync(string Username, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : Hugo_LAND.Client.HugoLandServices.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IAccountService>, Hugo_LAND.Client.HugoLandServices.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authentification(string Username, string Password) {
            return base.Channel.Authentification(Username, Password);
        }
        
        public System.Threading.Tasks.Task<string> AuthentificationAsync(string Username, string Password) {
            return base.Channel.AuthentificationAsync(Username, Password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IClassService")]
    public interface IClassService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetClasse", ReplyAction="http://tempuri.org/IClassService/GetClasseResponse")]
        Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[] GetClasse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetClasse", ReplyAction="http://tempuri.org/IClassService/GetClasseResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[]> GetClasseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/CreerClasse", ReplyAction="http://tempuri.org/IClassService/CreerClasseResponse")]
        void CreerClasse(string nom, string description, int str, int dex, int ints, int vit, int idMonde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/CreerClasse", ReplyAction="http://tempuri.org/IClassService/CreerClasseResponse")]
        System.Threading.Tasks.Task CreerClasseAsync(string nom, string description, int str, int dex, int ints, int vit, int idMonde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/SupprimeClasse", ReplyAction="http://tempuri.org/IClassService/SupprimeClasseResponse")]
        void SupprimeClasse(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/SupprimeClasse", ReplyAction="http://tempuri.org/IClassService/SupprimeClasseResponse")]
        System.Threading.Tasks.Task SupprimeClasseAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassServiceChannel : Hugo_LAND.Client.HugoLandServices.IClassService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IClassService>, Hugo_LAND.Client.HugoLandServices.IClassService {
        
        public ClassServiceClient() {
        }
        
        public ClassServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[] GetClasse() {
            return base.Channel.GetClasse();
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[]> GetClasseAsync() {
            return base.Channel.GetClasseAsync();
        }
        
        public void CreerClasse(string nom, string description, int str, int dex, int ints, int vit, int idMonde) {
            base.Channel.CreerClasse(nom, description, str, dex, ints, vit, idMonde);
        }
        
        public System.Threading.Tasks.Task CreerClasseAsync(string nom, string description, int str, int dex, int ints, int vit, int idMonde) {
            return base.Channel.CreerClasseAsync(nom, description, str, dex, ints, vit, idMonde);
        }
        
        public void SupprimeClasse(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto) {
            base.Channel.SupprimeClasse(dto);
        }
        
        public System.Threading.Tasks.Task SupprimeClasseAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto) {
            return base.Channel.SupprimeClasseAsync(dto);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IHeroService")]
    public interface IHeroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/RetourneHerosCompte", ReplyAction="http://tempuri.org/IHeroService/RetourneHerosCompteResponse")]
        Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[] RetourneHerosCompte(int idCompteJoueur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/RetourneHerosCompte", ReplyAction="http://tempuri.org/IHeroService/RetourneHerosCompteResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[]> RetourneHerosCompteAsync(int idCompteJoueur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/CreeHero", ReplyAction="http://tempuri.org/IHeroService/CreeHeroResponse")]
        void CreeHero(string newNomHero, bool newConnection, int idClasse, int idCompteJoueur, int idMonde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/CreeHero", ReplyAction="http://tempuri.org/IHeroService/CreeHeroResponse")]
        System.Threading.Tasks.Task CreeHeroAsync(string newNomHero, bool newConnection, int idClasse, int idCompteJoueur, int idMonde);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/SupprimeHero", ReplyAction="http://tempuri.org/IHeroService/SupprimeHeroResponse")]
        void SupprimeHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/SupprimeHero", ReplyAction="http://tempuri.org/IHeroService/SupprimeHeroResponse")]
        System.Threading.Tasks.Task SupprimeHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/DeplaceHero", ReplyAction="http://tempuri.org/IHeroService/DeplaceHeroResponse")]
        void DeplaceHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/DeplaceHero", ReplyAction="http://tempuri.org/IHeroService/DeplaceHeroResponse")]
        System.Threading.Tasks.Task DeplaceHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeroServiceChannel : Hugo_LAND.Client.HugoLandServices.IHeroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeroServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IHeroService>, Hugo_LAND.Client.HugoLandServices.IHeroService {
        
        public HeroServiceClient() {
        }
        
        public HeroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[] RetourneHerosCompte(int idCompteJoueur) {
            return base.Channel.RetourneHerosCompte(idCompteJoueur);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[]> RetourneHerosCompteAsync(int idCompteJoueur) {
            return base.Channel.RetourneHerosCompteAsync(idCompteJoueur);
        }
        
        public void CreeHero(string newNomHero, bool newConnection, int idClasse, int idCompteJoueur, int idMonde) {
            base.Channel.CreeHero(newNomHero, newConnection, idClasse, idCompteJoueur, idMonde);
        }
        
        public System.Threading.Tasks.Task CreeHeroAsync(string newNomHero, bool newConnection, int idClasse, int idCompteJoueur, int idMonde) {
            return base.Channel.CreeHeroAsync(newNomHero, newConnection, idClasse, idCompteJoueur, idMonde);
        }
        
        public void SupprimeHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto) {
            base.Channel.SupprimeHero(dto);
        }
        
        public System.Threading.Tasks.Task SupprimeHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto) {
            return base.Channel.SupprimeHeroAsync(dto);
        }
        
        public void DeplaceHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY) {
            base.Channel.DeplaceHero(dto, newX, newY);
        }
        
        public System.Threading.Tasks.Task DeplaceHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY) {
            return base.Channel.DeplaceHeroAsync(dto, newX, newY);
        }
    }
}
