//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hugo_LAND.Client.HugoLandServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_LAND.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class AccountDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Hugo_LAND.Core.Models.TypeUtilisateur TypeUtilisateurField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Hugo_LAND.Core.Models.TypeUtilisateur TypeUtilisateur {
            get {
                return this.TypeUtilisateurField;
            }
            set {
                if ((this.TypeUtilisateurField.Equals(value) != true)) {
                    this.TypeUtilisateurField = value;
                    this.RaisePropertyChanged("TypeUtilisateur");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_LAND.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class ClassDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseDexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatBaseVitalityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClassName {
            get {
                return this.ClassNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassNameField, value) != true)) {
                    this.ClassNameField = value;
                    this.RaisePropertyChanged("ClassName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseDex {
            get {
                return this.StatBaseDexField;
            }
            set {
                if ((this.StatBaseDexField.Equals(value) != true)) {
                    this.StatBaseDexField = value;
                    this.RaisePropertyChanged("StatBaseDex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseReg {
            get {
                return this.StatBaseRegField;
            }
            set {
                if ((this.StatBaseRegField.Equals(value) != true)) {
                    this.StatBaseRegField = value;
                    this.RaisePropertyChanged("StatBaseReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseStr {
            get {
                return this.StatBaseStrField;
            }
            set {
                if ((this.StatBaseStrField.Equals(value) != true)) {
                    this.StatBaseStrField = value;
                    this.RaisePropertyChanged("StatBaseStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatBaseVitality {
            get {
                return this.StatBaseVitalityField;
            }
            set {
                if ((this.StatBaseVitalityField.Equals(value) != true)) {
                    this.StatBaseVitalityField = value;
                    this.RaisePropertyChanged("StatBaseVitality");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorldDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_LAND.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class WorldDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LimiteXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LimiteYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimiteX {
            get {
                return this.LimiteXField;
            }
            set {
                if ((this.LimiteXField.Equals(value) != true)) {
                    this.LimiteXField = value;
                    this.RaisePropertyChanged("LimiteX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LimiteY {
            get {
                return this.LimiteYField;
            }
            set {
                if ((this.LimiteYField.Equals(value) != true)) {
                    this.LimiteYField = value;
                    this.RaisePropertyChanged("LimiteY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeroDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_LAND.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class HeroDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExperienceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeroNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatDexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatRegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatStrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatVitalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isConnectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Experience {
            get {
                return this.ExperienceField;
            }
            set {
                if ((this.ExperienceField.Equals(value) != true)) {
                    this.ExperienceField = value;
                    this.RaisePropertyChanged("Experience");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeroName {
            get {
                return this.HeroNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HeroNameField, value) != true)) {
                    this.HeroNameField = value;
                    this.RaisePropertyChanged("HeroName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatDex {
            get {
                return this.StatDexField;
            }
            set {
                if ((this.StatDexField.Equals(value) != true)) {
                    this.StatDexField = value;
                    this.RaisePropertyChanged("StatDex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatReg {
            get {
                return this.StatRegField;
            }
            set {
                if ((this.StatRegField.Equals(value) != true)) {
                    this.StatRegField = value;
                    this.RaisePropertyChanged("StatReg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatStr {
            get {
                return this.StatStrField;
            }
            set {
                if ((this.StatStrField.Equals(value) != true)) {
                    this.StatStrField = value;
                    this.RaisePropertyChanged("StatStr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatVitality {
            get {
                return this.StatVitalityField;
            }
            set {
                if ((this.StatVitalityField.Equals(value) != true)) {
                    this.StatVitalityField = value;
                    this.RaisePropertyChanged("StatVitality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string World {
            get {
                return this.WorldField;
            }
            set {
                if ((object.ReferenceEquals(this.WorldField, value) != true)) {
                    this.WorldField = value;
                    this.RaisePropertyChanged("World");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isConnected {
            get {
                return this.isConnectedField;
            }
            set {
                if ((this.isConnectedField.Equals(value) != true)) {
                    this.isConnectedField = value;
                    this.RaisePropertyChanged("isConnected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorldItemDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_LAND.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class WorldItemDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WorldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeObject {
            get {
                return this.TypeObjectField;
            }
            set {
                if ((this.TypeObjectField.Equals(value) != true)) {
                    this.TypeObjectField = value;
                    this.RaisePropertyChanged("TypeObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int World {
            get {
                return this.WorldField;
            }
            set {
                if ((this.WorldField.Equals(value) != true)) {
                    this.WorldField = value;
                    this.RaisePropertyChanged("World");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonsterDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_LAND.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class MonsterDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NiveauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float StatDmgMaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float StatDmgMinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatPVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((this.ImageIdField.Equals(value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Niveau {
            get {
                return this.NiveauField;
            }
            set {
                if ((this.NiveauField.Equals(value) != true)) {
                    this.NiveauField = value;
                    this.RaisePropertyChanged("Niveau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float StatDmgMax {
            get {
                return this.StatDmgMaxField;
            }
            set {
                if ((this.StatDmgMaxField.Equals(value) != true)) {
                    this.StatDmgMaxField = value;
                    this.RaisePropertyChanged("StatDmgMax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float StatDmgMin {
            get {
                return this.StatDmgMinField;
            }
            set {
                if ((this.StatDmgMinField.Equals(value) != true)) {
                    this.StatDmgMinField = value;
                    this.RaisePropertyChanged("StatDmgMin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatPV {
            get {
                return this.StatPVField;
            }
            set {
                if ((this.StatPVField.Equals(value) != true)) {
                    this.StatPVField = value;
                    this.RaisePropertyChanged("StatPV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemDetailsDTO", Namespace="http://schemas.datacontract.org/2004/07/Hugo_LAND.WCF.DTOs")]
    [System.SerializableAttribute()]
    public partial class ItemDetailsDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ImageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> xField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> yField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ImageId {
            get {
                return this.ImageIdField;
            }
            set {
                if ((this.ImageIdField.Equals(value) != true)) {
                    this.ImageIdField = value;
                    this.RaisePropertyChanged("ImageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom {
            get {
                return this.NomField;
            }
            set {
                if ((object.ReferenceEquals(this.NomField, value) != true)) {
                    this.NomField = value;
                    this.RaisePropertyChanged("Nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> x {
            get {
                return this.xField;
            }
            set {
                if ((this.xField.Equals(value) != true)) {
                    this.xField = value;
                    this.RaisePropertyChanged("x");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> y {
            get {
                return this.yField;
            }
            set {
                if ((this.yField.Equals(value) != true)) {
                    this.yField = value;
                    this.RaisePropertyChanged("y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IAccountService")]
    public interface IAccountService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Authentification", ReplyAction="http://tempuri.org/IAccountService/AuthentificationResponse")]
        string Authentification(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/Authentification", ReplyAction="http://tempuri.org/IAccountService/AuthentificationResponse")]
        System.Threading.Tasks.Task<string> AuthentificationAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetAccountInfoByUsername", ReplyAction="http://tempuri.org/IAccountService/GetAccountInfoByUsernameResponse")]
        Hugo_LAND.Client.HugoLandServices.AccountDetailsDTO GetAccountInfoByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountService/GetAccountInfoByUsername", ReplyAction="http://tempuri.org/IAccountService/GetAccountInfoByUsernameResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.AccountDetailsDTO> GetAccountInfoByUsernameAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountServiceChannel : Hugo_LAND.Client.HugoLandServices.IAccountService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IAccountService>, Hugo_LAND.Client.HugoLandServices.IAccountService {
        
        public AccountServiceClient() {
        }
        
        public AccountServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Authentification(string Username, string Password) {
            return base.Channel.Authentification(Username, Password);
        }
        
        public System.Threading.Tasks.Task<string> AuthentificationAsync(string Username, string Password) {
            return base.Channel.AuthentificationAsync(Username, Password);
        }
        
        public Hugo_LAND.Client.HugoLandServices.AccountDetailsDTO GetAccountInfoByUsername(string username) {
            return base.Channel.GetAccountInfoByUsername(username);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.AccountDetailsDTO> GetAccountInfoByUsernameAsync(string username) {
            return base.Channel.GetAccountInfoByUsernameAsync(username);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IClassService")]
    public interface IClassService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetAllClasses", ReplyAction="http://tempuri.org/IClassService/GetAllClassesResponse")]
        Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[] GetAllClasses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetAllClasses", ReplyAction="http://tempuri.org/IClassService/GetAllClassesResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[]> GetAllClassesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/CreateClass", ReplyAction="http://tempuri.org/IClassService/CreateClassResponse")]
        bool CreateClass(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO newClass, Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO world);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/CreateClass", ReplyAction="http://tempuri.org/IClassService/CreateClassResponse")]
        System.Threading.Tasks.Task<bool> CreateClassAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO newClass, Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO world);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/DeleteClass", ReplyAction="http://tempuri.org/IClassService/DeleteClassResponse")]
        bool DeleteClass(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/DeleteClass", ReplyAction="http://tempuri.org/IClassService/DeleteClassResponse")]
        System.Threading.Tasks.Task<bool> DeleteClassAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/SaveClass", ReplyAction="http://tempuri.org/IClassService/SaveClassResponse")]
        bool SaveClass(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/SaveClass", ReplyAction="http://tempuri.org/IClassService/SaveClassResponse")]
        System.Threading.Tasks.Task<bool> SaveClassAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetClassByName", ReplyAction="http://tempuri.org/IClassService/GetClassByNameResponse")]
        Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO GetClassByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassService/GetClassByName", ReplyAction="http://tempuri.org/IClassService/GetClassByNameResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO> GetClassByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClassServiceChannel : Hugo_LAND.Client.HugoLandServices.IClassService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClassServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IClassService>, Hugo_LAND.Client.HugoLandServices.IClassService {
        
        public ClassServiceClient() {
        }
        
        public ClassServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClassServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[] GetAllClasses() {
            return base.Channel.GetAllClasses();
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO[]> GetAllClassesAsync() {
            return base.Channel.GetAllClassesAsync();
        }
        
        public bool CreateClass(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO newClass, Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO world) {
            return base.Channel.CreateClass(newClass, world);
        }
        
        public System.Threading.Tasks.Task<bool> CreateClassAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO newClass, Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO world) {
            return base.Channel.CreateClassAsync(newClass, world);
        }
        
        public bool DeleteClass(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto) {
            return base.Channel.DeleteClass(dto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClassAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto) {
            return base.Channel.DeleteClassAsync(dto);
        }
        
        public bool SaveClass(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto) {
            return base.Channel.SaveClass(dto);
        }
        
        public System.Threading.Tasks.Task<bool> SaveClassAsync(Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO dto) {
            return base.Channel.SaveClassAsync(dto);
        }
        
        public Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO GetClassByName(string name) {
            return base.Channel.GetClassByName(name);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ClassDetailsDTO> GetClassByNameAsync(string name) {
            return base.Channel.GetClassByNameAsync(name);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IHeroService")]
    public interface IHeroService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/ReturnHerosFromAccount", ReplyAction="http://tempuri.org/IHeroService/ReturnHerosFromAccountResponse")]
        Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[] ReturnHerosFromAccount(int idCompteJoueur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/ReturnHerosFromAccount", ReplyAction="http://tempuri.org/IHeroService/ReturnHerosFromAccountResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[]> ReturnHerosFromAccountAsync(int idCompteJoueur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/CreateHero", ReplyAction="http://tempuri.org/IHeroService/CreateHeroResponse")]
        bool CreateHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/CreateHero", ReplyAction="http://tempuri.org/IHeroService/CreateHeroResponse")]
        System.Threading.Tasks.Task<bool> CreateHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/DeleteHero", ReplyAction="http://tempuri.org/IHeroService/DeleteHeroResponse")]
        bool DeleteHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/DeleteHero", ReplyAction="http://tempuri.org/IHeroService/DeleteHeroResponse")]
        System.Threading.Tasks.Task<bool> DeleteHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/MoveHero", ReplyAction="http://tempuri.org/IHeroService/MoveHeroResponse")]
        void MoveHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/MoveHero", ReplyAction="http://tempuri.org/IHeroService/MoveHeroResponse")]
        System.Threading.Tasks.Task MoveHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/ReturnHero", ReplyAction="http://tempuri.org/IHeroService/ReturnHeroResponse")]
        Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO ReturnHero(string idhero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/ReturnHero", ReplyAction="http://tempuri.org/IHeroService/ReturnHeroResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO> ReturnHeroAsync(string idhero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/ConnectHero", ReplyAction="http://tempuri.org/IHeroService/ConnectHeroResponse")]
        string ConnectHero(bool isConnected, int idHero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHeroService/ConnectHero", ReplyAction="http://tempuri.org/IHeroService/ConnectHeroResponse")]
        System.Threading.Tasks.Task<string> ConnectHeroAsync(bool isConnected, int idHero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHeroServiceChannel : Hugo_LAND.Client.HugoLandServices.IHeroService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HeroServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IHeroService>, Hugo_LAND.Client.HugoLandServices.IHeroService {
        
        public HeroServiceClient() {
        }
        
        public HeroServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HeroServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HeroServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[] ReturnHerosFromAccount(int idCompteJoueur) {
            return base.Channel.ReturnHerosFromAccount(idCompteJoueur);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO[]> ReturnHerosFromAccountAsync(int idCompteJoueur) {
            return base.Channel.ReturnHerosFromAccountAsync(idCompteJoueur);
        }
        
        public bool CreateHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto) {
            return base.Channel.CreateHero(dto);
        }
        
        public System.Threading.Tasks.Task<bool> CreateHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto) {
            return base.Channel.CreateHeroAsync(dto);
        }
        
        public bool DeleteHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto) {
            return base.Channel.DeleteHero(dto);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto) {
            return base.Channel.DeleteHeroAsync(dto);
        }
        
        public void MoveHero(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY) {
            base.Channel.MoveHero(dto, newX, newY);
        }
        
        public System.Threading.Tasks.Task MoveHeroAsync(Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO dto, int newX, int newY) {
            return base.Channel.MoveHeroAsync(dto, newX, newY);
        }
        
        public Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO ReturnHero(string idhero) {
            return base.Channel.ReturnHero(idhero);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.HeroDetailsDTO> ReturnHeroAsync(string idhero) {
            return base.Channel.ReturnHeroAsync(idhero);
        }
        
        public string ConnectHero(bool isConnected, int idHero) {
            return base.Channel.ConnectHero(isConnected, idHero);
        }
        
        public System.Threading.Tasks.Task<string> ConnectHeroAsync(bool isConnected, int idHero) {
            return base.Channel.ConnectHeroAsync(isConnected, idHero);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IWorldService")]
    public interface IWorldService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorldService/GetAllWorldNames", ReplyAction="http://tempuri.org/IWorldService/GetAllWorldNamesResponse")]
        Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO[] GetAllWorldNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorldService/GetAllWorldNames", ReplyAction="http://tempuri.org/IWorldService/GetAllWorldNamesResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO[]> GetAllWorldNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorldService/GetWorldByName", ReplyAction="http://tempuri.org/IWorldService/GetWorldByNameResponse")]
        Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO GetWorldByName(string worldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorldService/GetWorldByName", ReplyAction="http://tempuri.org/IWorldService/GetWorldByNameResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO> GetWorldByNameAsync(string worldName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorldServiceChannel : Hugo_LAND.Client.HugoLandServices.IWorldService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorldServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IWorldService>, Hugo_LAND.Client.HugoLandServices.IWorldService {
        
        public WorldServiceClient() {
        }
        
        public WorldServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorldServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO[] GetAllWorldNames() {
            return base.Channel.GetAllWorldNames();
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO[]> GetAllWorldNamesAsync() {
            return base.Channel.GetAllWorldNamesAsync();
        }
        
        public Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO GetWorldByName(string worldName) {
            return base.Channel.GetWorldByName(worldName);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.WorldDetailsDTO> GetWorldByNameAsync(string worldName) {
            return base.Channel.GetWorldByNameAsync(worldName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IWorldItemService")]
    public interface IWorldItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorldItemService/ReturnWorldItems", ReplyAction="http://tempuri.org/IWorldItemService/ReturnWorldItemsResponse")]
        Hugo_LAND.Client.HugoLandServices.WorldItemDetailsDTO[] ReturnWorldItems(string world, int mapBeginX, int mapBeginY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorldItemService/ReturnWorldItems", ReplyAction="http://tempuri.org/IWorldItemService/ReturnWorldItemsResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.WorldItemDetailsDTO[]> ReturnWorldItemsAsync(string world, int mapBeginX, int mapBeginY);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorldItemServiceChannel : Hugo_LAND.Client.HugoLandServices.IWorldItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorldItemServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IWorldItemService>, Hugo_LAND.Client.HugoLandServices.IWorldItemService {
        
        public WorldItemServiceClient() {
        }
        
        public WorldItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorldItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorldItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.WorldItemDetailsDTO[] ReturnWorldItems(string world, int mapBeginX, int mapBeginY) {
            return base.Channel.ReturnWorldItems(world, mapBeginX, mapBeginY);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.WorldItemDetailsDTO[]> ReturnWorldItemsAsync(string world, int mapBeginX, int mapBeginY) {
            return base.Channel.ReturnWorldItemsAsync(world, mapBeginX, mapBeginY);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IMonsterService")]
    public interface IMonsterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/ReturnMonsters", ReplyAction="http://tempuri.org/IMonsterService/ReturnMonstersResponse")]
        Hugo_LAND.Client.HugoLandServices.MonsterDetailsDTO[] ReturnMonsters(string world, int mapBeginX, int mapBeginY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonsterService/ReturnMonsters", ReplyAction="http://tempuri.org/IMonsterService/ReturnMonstersResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.MonsterDetailsDTO[]> ReturnMonstersAsync(string world, int mapBeginX, int mapBeginY);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonsterServiceChannel : Hugo_LAND.Client.HugoLandServices.IMonsterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonsterServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IMonsterService>, Hugo_LAND.Client.HugoLandServices.IMonsterService {
        
        public MonsterServiceClient() {
        }
        
        public MonsterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonsterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonsterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonsterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.MonsterDetailsDTO[] ReturnMonsters(string world, int mapBeginX, int mapBeginY) {
            return base.Channel.ReturnMonsters(world, mapBeginX, mapBeginY);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.MonsterDetailsDTO[]> ReturnMonstersAsync(string world, int mapBeginX, int mapBeginY) {
            return base.Channel.ReturnMonstersAsync(world, mapBeginX, mapBeginY);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HugoLandServices.IItemService")]
    public interface IItemService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/ReturnItems", ReplyAction="http://tempuri.org/IItemService/ReturnItemsResponse")]
        Hugo_LAND.Client.HugoLandServices.ItemDetailsDTO[] ReturnItems(string world, int mapBeginX, int mapBeginY);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IItemService/ReturnItems", ReplyAction="http://tempuri.org/IItemService/ReturnItemsResponse")]
        System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ItemDetailsDTO[]> ReturnItemsAsync(string world, int mapBeginX, int mapBeginY);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IItemServiceChannel : Hugo_LAND.Client.HugoLandServices.IItemService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItemServiceClient : System.ServiceModel.ClientBase<Hugo_LAND.Client.HugoLandServices.IItemService>, Hugo_LAND.Client.HugoLandServices.IItemService {
        
        public ItemServiceClient() {
        }
        
        public ItemServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItemServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Hugo_LAND.Client.HugoLandServices.ItemDetailsDTO[] ReturnItems(string world, int mapBeginX, int mapBeginY) {
            return base.Channel.ReturnItems(world, mapBeginX, mapBeginY);
        }
        
        public System.Threading.Tasks.Task<Hugo_LAND.Client.HugoLandServices.ItemDetailsDTO[]> ReturnItemsAsync(string world, int mapBeginX, int mapBeginY) {
            return base.Channel.ReturnItemsAsync(world, mapBeginX, mapBeginY);
        }
    }
}
